export const SHEETS_ADD_DATA = "SHEETS_ADD_DATA";
export const SHEETS_ADD_DATA_PENDING = "SHEETS_ADD_DATA_PENDING";

export const SHEETS_GET_DATA = "SHEETS_GET_DATA";
export const SHEETS_GET_DATA_PENDING = "SHEETS_GET_DATA_PENDING";

export const SHEETS_ERROR = "SHEETS_ERROR";
